### ISSUE TITLE
Mobile browser issue

### ISSUE THREAD

**Issue by ax4625** [aharen/thaana-keyboard#8]
not working in mobile browsers

**Comment by aharen** [comment]
Hi. Can you please share some more information. Browser / OS etc.

**Comment by ax4625** [comment]
thanks for the reply:
It's Android, chrome. tried using my phone only
check the below screenshots for the result
https://ibb.co/gvJMgSJ

**Comment by aharen** [comment]
Ah! This issue was due to Android auto-complete. I believed it to be fixed but seems not the case :/

I have pushed an update to the following branch.

[https://github.com/aharen/thaana-keyboard/tree/android-input-issue](https://github.com/aharen/thaana-keyboard/tree/android-input-issue)

Unfortunately, i don't have access to an Android at the moment to test this out. Would be awesome if you could test/help with a fix :)

Thanks

**Comment by ax4625** [comment]
Hello,
In Android version 10 works fine without space in a single word. But with space, it changes into English letters. Android version 12 does not appear to be fixed, as before.

Thanks

**Comment by aharen** [comment]
i've pushed an update versioned 2.0.4 can you please check if that resolves the issue

**Comment by ax4625** [comment]
looks like the same issue on android 12

created this and works fine for all browsers
thanks for the support
https://github.com/ax4625/React-Thaana-Keyboard

**Comment by aharen** [comment]
Ah! I see :/ maybe i'll work a bit more when i get access to an Android.

Awesome implementation. Works for most cases. 

The one thing i was trying to address were scenarios where copy paste of english words, characters.. like URL

That maybe needs a re-think.

Thanks :)

**Comment by Z3d0X** [comment]
I tested on Android 12 Chrome using both samsung & google keyboard. It works fine on samsung keyboard, but has issues in google keyboard.

Attacted are InputEvents of both captured via chrome remote debugging

Google Keyboard (GBoard):
<img width="319" alt="google-keyboard" src="https://user-images.githubusercontent.com/75579178/163128291-2347cc7e-c0e2-41cb-8a91-a1e1d5b4939c.png">

Samsung Keyboard:
<img width="315" alt="samsung-keyboard" src="https://user-images.githubusercontent.com/75579178/163128374-7ddb9d5d-a35d-45f2-a9ac-f59f1610a971.png">



https://github.com/aharen/thaana-keyboard/blob/27a0c51c26ebaa84c9e0002980626fb622261614/ThaanaKeyboard.js#L17-L26

changing `this.latinChar = e.data;` to `this.latinChar = e.data.charAt(e.data.length - 1);` fixed the issue for me on google keyboard

**Comment by aharen** [comment]
@ZedoXmv That's a very interesting find. Thank you! :D 

I have just published a new version implementing your suggestion - [v2.0.6](https://github.com/aharen/thaana-keyboard/releases/tag/v2.0.6)

Can you please confirm it works? :)

**Comment by Z3d0X** [comment]
Tested on the [demo](https://thaana-keyboard.khusaam.com/). Seems to be working fine. 👍

**Comment by ax4625** [comment]
works fine for Android 12 google Gboard.  tested on this demo

**Comment by aharen** [comment]
Thanks a lot guys 🙏 @ax4625 @ZedoXmv
